site_name: Afiz Tech
site_url: https://www.youtube.com/channel/UCeDb05CCWRs6AQJNiiQiP3g?sub_confirmation=1
nav:
- Home: 'index.md'
- Projects:
    - 'School Management System': 'projects/sms.md'
    - 'Restaurant Management System': 'projects/rms.md'
    - 'URL Shortner Proejct': 'projects/url.md'
repo_url: https://github.com/afizs/afiz-tech
repo_name: afizs/afiz-tech
theme:
  language: en
  name: material
  logo: assets/afiz-logo.png
  palette:
  - media: '(prefers-color-scheme: dark)'
    scheme: default
    primary: light-blue
    toggle:
        icon: material/lightbulb
        name: Switch to light mode
    # dark mode
  - media: '(prefers-color-scheme: light)'
    scheme: slate
    primary: teal
    toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  features:
    - navigation.top
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.snippets


